### ISSUE TITLE
Implementation of additional filters

### ISSUE THREAD

**Issue by johanna-mohr** [OpenEnergyPlatform/django-comparison-dashboard#28]
With Sankey-diagrams, the problem has occurred that no diagram is loaded when filtering by both input and output groups.
If only one of the groups is filtered, a Sankey-diagram with only this group is created, the other one does not appear (see the following diagram).
![in_plot](https://github.com/user-attachments/assets/94902d28-3a7a-44d2-b924-7f401bbbf11a)
Only if neither is filtered a diagram with both input and output is generated, which, however, becomes confusing as a result (see the following diagram).
![in_out_plot](https://github.com/user-attachments/assets/b592fa75-ecc6-4a47-9a61-4ce1902dfb7d)
When analyzing the problem, the idea arose that it would be helpful to have a function that allows you to select which input/output groups should not be considered and not just the function where you select which should be considered. This way it would be possible to reduce the large diagram in a targeted manner.
Furthermore, it would be good, especially for Sankey-diagrams, to have the option to filter by unit so that the flow can be displayed correctly.

**Comment by bereba** [comment]
Thank you for the comprehensive description. We are working on this.

A possible problem for the unit filtering: So far it takes place before the unit conversion (e.g. from PJ to TWh).
This should be considered when applying the filter to be able to consider possible different energy units in the same sankey.
